version: 2.1
jobs:
  tests:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      
      - restore_cache:
         keys:
           - v1-dependencies-{{ checksum "package.json" }}
           - v1-dependencies-

      - save_cache:
         paths:
           - node_modules
         key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install Dependencies
          command: yarn install
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Format Check
          command: yarn format:check
      - run:
          name: Test
          command: yarn test
      - run:
          name: Coverage Threshold Check
          command: yarn test:cov
      - run:
          name: End to end test
          command: yarn test:e2e
          
  build-publish-deploy-stage:
    description: Build docker image and push to gcr registry
    docker:
      - image: google/cloud-sdk
     
    steps:
      - checkout
      - gcp-gcr/gcr-auth:
          gcloud-service-key: GCLOUD_SERVICE_KEY
          google-project-id: GOOGLE_PROJECT_ID
          google-compute-zone: GOOGLE_COMPUTE_ZONE
      - cloudrun/build:
          tag: 'gcr.io/${GOOGLE_PROJECT_ID}/suleparlat/atolye-15-demo:latest'
      - cloudrun/deploy:
          platform: "gke"
          image: "gcr.io/${GOOGLE_PROJECT_ID}/suleparlat/atolye-15-demo:latest"
          cluster: sule-atolye-15
          namespace: stage
          service-name: next-webapp
          cluster-location: us-central1-c
          
orbs:
  gcp-gcr: circleci/gcp-gcr@0.13.0
  gcp-gke: circleci/gcp-gke@0.1.0
  cloudrun: circleci/gcp-cloud-run@1.0.0
          
workflows:
  version: 2
  test-and-publish-stage:
    jobs:
      - tests
      - build-publish-deploy-stage:
          requires:
            - tests
          filters:
            branches:
              only: develop

  
