version: 2.1
jobs:
  tests:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Format Check
          command: yarn format:check
      - run:
          name: Test
          command: yarn test
      - run:
          name: Coverage Threshold Check
          command: yarn test:cov
      - run:
          name: End to end test
          command: yarn test:e2e
          
  build-publish:
    description: Build docker image and push to gcr registry
    executor: machine-executor
    environment:
      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
      GOOGLE_COMPUTE_ZONE: ${{ secrets.GOOGLE_COMPUTE_ZONE }}
      GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      CLOUDSDK_PYTHON: ${{ secrets.CLOUDSDK_PYTHON }}
    steps:
      - checkout
      
      - gcp-gcr/gcr-auth:
          gcloud-service-key: GCLOUD_SERVICE_KEY
          google-project-id: GOOGLE_PROJECT_ID
          google-compute-zone: GOOGLE_COMPUTE_ZONE

      - gcp-gcr/build-image:
          dockerfile: Dockerfile
          google-project-id: GOOGLE_PROJECT_ID
          image: sule
          registry-url: "gcr.io"
          tag: latest
      - gcp-gcr/push-image:
          google-project-id: GOOGLE_PROJECT_ID
          image: sule
          registry-url: "gcr.io"
          tag: latest

orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
  cloudrun: circleci/gcp-cloud-run@1.0.1
  gcp-gke: circleci/gcp-gke@0.2.0
executors:
  gcloud-executor:
    docker:
      - image: google/cloud-sdk
  machine-executor:
    machine: true
          
workflows:
  version: 2
  test-and-publish:
    jobs:
      - tests
      - build-publish:
          requires:
            - tests
          filters:
            branches:
              only: develop
  
