version: 2.1
jobs:
  tests:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      
      - restore_cache:
         keys:
           - v1-dependencies-{{ checksum "package.json" }}
           - v1-dependencies-

      - save_cache:
         paths:
           - node_modules
         key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install Dependencies
          command: yarn install
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Format Check
          command: yarn format:check
      - run:
          name: Test
          command: yarn test
      - run:
          name: Coverage Threshold Check
          command: yarn test:cov
      - run:
          name: End to end test
          command: yarn test:e2e
          
  build-publish:
    description: Build docker image and push to gcr registry
    executor: machine-executor
    environment:
      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
      GOOGLE_COMPUTE_ZONE: ${{ secrets.GOOGLE_COMPUTE_ZONE }}
      GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      CLOUDSDK_PYTHON: ${{ secrets.CLOUDSDK_PYTHON }}
      LD_LIBRARY_PATH: ${{ secrets.LD_LIBRARY_PATH }}

    - checkout
    - run:
        name: Build Docker image 
        command: docker build --target builder -t suleparlat/atolye-15-demo:lasest . && docker build --target installer -t suleparlat/atolye-15-demo:lasest .
    - gcp-gcr/gcr-auth:
        gcloud-service-key: GCLOUD_SERVICE_KEY
        google-project-id: GOOGLE_PROJECT_ID
        google-compute-zone: GOOGLE_COMPUTE_ZONE
    - cloudrun/deploy:
        platform: 'managed'
        image: 'suleparlat/atolye-15-demo:lasest'
        service-name: 'orb-gcp-cloud-run'
        region: $GOOGLE_COMPUTE_ZONE
        unauthenticated: true
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
  cloudrun: circleci/gcp-cloud-run@1.0.0
          
workflows:
  version: 2
  test-and-publish:
    jobs:
      - tests
      - build-publish:
          requires:
            - tests
          filters:
            branches:
              only: develop
  
